config/routes.rb
Rails.application.routes.draw do

  get "/products/new" => "products#new", as: :new_product
  post "/products" => "products#create", as: :products
  get "/products/:id" => "products#show", as: :product
  get "/products" => "products#index"
  get "/products/:id/edit" => "products#edit", as: :edit_product
  patch "/products/:id" => "products#update"
  delete "/products/:id" => "products#destroy"

  resources :products do
    resources :comments, only: [:create,:destroy,:index] do
      resources :likes, only: [:create, :destroy]
    end
    resources :favourites, only: [:create,:destroy]
    end
    resources :favourites, only: :index
  resources :sessions, only: [:new,:create,:destroy]
  resources :users, only: [:new,:create, :destroy]

  root "products#index"

end

app/models/like.rb
class Like < ActiveRecord::Base
  belongs_to :comment
  belongs_to :user
end

app/controllers/likes_controller.rb
class LikesController < ApplicationController

  def create
    @product = Product.find params[:product_id]
    @comment = Comment.find params[:comment_id]
    like = Like.new
    like.user = current_user
    like.comment = @comment
    respond_to do |format|
        if like.save
        format.html{redirect_to product_path(@product), notice: "You liked a comment"}
        format.js {render}
      else
        format.html {redirect_to product_path(@product), notice: "Failed to like a comment"}
      end
    end
  end

  def destroy
    @product = Product.find params[:product_id]
    @like = Like.find params[:id]
    @comment = Comment.find params[:comment_id]
    @like.destroy
    respond_to do |format|
      format.html{redirect_to product_path(@product), notice: "You have unliked a comment"}
      format.js {render}
    end
  end

end

app/helpers/likes_helper.rb
module LikesHelper
end

app/views/likes/_like.html.erb
<% if user_like(c) %>
<div id="<%=dom_id(user_like(c))%>">
<%= link_to "Unlike", product_comment_like_path(@product, c.id, user_like(c.id)), method: :delete, remote:true %>
(<%= c.likes.count%>)
</div>
<%else%>
<%= link_to "Like", product_comment_likes_path(@product,c), method: :post, remote:true%>
(<%= c.likes.count%>)
<%end%>
</div>

app/views/likes/create.js.erb
$("#like-<%=dom_id(@comment)%>").html("<%= j render 'like', c: @comment%>")

app/views/likes/destroy.js.erb
$("#<%=dom_id(@like)%>").html("<%= j render 'like',c: @comment %>")
// $("#like-<%=dom_id(@comment)%>").html("<%= j render 'like', c: @comment%>")