config/routes.rb
Rails.application.routes.draw do

  get "/products/new" => "products#new", as: :new_product
  post "/products" => "products#create", as: :products
  get "/products/:id" => "products#show", as: :product
  get "/products" => "products#index"
  get "/products/:id/edit" => "products#edit", as: :edit_product
  patch "/products/:id" => "products#update"
  delete "/products/:id" => "products#destroy"

  resources :products do
    resources :comments, only: [:create,:destroy,:index] do
      resources :likes, only: [:create, :destroy]
    end
    resources :favourites, only: [:create,:destroy]
    end
    resources :favourites, only: :index
  resources :sessions, only: [:new,:create,:destroy]
  resources :users, only: [:new,:create, :destroy]

  root "products#index"

end

app/models/favourite.rb
class Favourite < ActiveRecord::Base
  belongs_to :product
  belongs_to :user

  def favourite_for(user)
    favourites.find_by_user_id user if user
  end
  
end

app/controllers/favourites_controller.rb
class FavouritesController < ApplicationController
  before_action :authenticate_user!

  def create
    @product = Product.find params[:product_id]
    favourite = Favourite.new
    favourite.product = @product
    favourite.user = current_user
    # byebug
    respond_to do |format|
        if favourite.save
        format.html {redirect_to product_path(@product), notice: "You have favourited this product"}
        format.js {render}
      else
        format.html{redirect_to product_path(@product), notice: "Failed to favourite this product"}
      end
    end
  end

  def destroy
    @product = Product.find params[:product_id]
    favourite = Favourite.find params[:id]
    favourite.destroy
    respond_to do |format|
      format.html {redirect_to product_path(@product), notice: "You have unfavourited this product"}
      format.js {render}
    end
  end

  def index
    @user= User.find current_user
    # byebug
  end
end

app/helpers/favourites_helper.rb
module FavouritesHelper
end

app/views/favourites/_favourite.html.erb
<%#byebug%>
<% if user_favourite %>
  <%= link_to "Unfavourite", product_favourite_path(@product, user_favourite), method: :delete,remote:true%>
<% else%>
<%= link_to "Favourite", product_favourites_path(@product), method: :post, remote:true%>
<% end%>
(<%= @product.favourites.count%>)

app/views/favourites/create.js.erb
$("#product-favourite").html("<%= j render 'favourite'%>")

app/views/favourites/destroy.js.erb
$("#product-favourite").html("<%= j render 'favourite'%>")

app/views/favourites/index.html.erb
<h1>Your Favourited Products</h1>
<% @user.favourites.each do |list| %>
  <div class="">
    <%= link_to list.product.title, product_path(list.product) %>
  </div>
<% end %>