config/routes.rb
Rails.application.routes.draw do

  get "/products/new" => "products#new", as: :new_product
  post "/products" => "products#create", as: :products
  get "/products/:id" => "products#show", as: :product
  get "/products" => "products#index"
  get "/products/:id/edit" => "products#edit", as: :edit_product
  patch "/products/:id" => "products#update"
  delete "/products/:id" => "products#destroy"

  resources :products do
    resources :comments, only: [:create,:destroy,:index] do
      resources :likes, only: [:create, :destroy]
    end
    resources :favourites, only: [:create,:destroy]
    end
    resources :favourites, only: :index
  resources :sessions, only: [:new,:create,:destroy]
  resources :users, only: [:new,:create, :destroy]

  root "products#index"

end

app/models/product.rb
class Product < ActiveRecord::Base

  has_many :comments, dependent: :destroy
  has_many :users, through: :favourites
  has_many :favourites, dependent: :nullify
  belongs_to :user

  validates :title,presence:true,uniqueness:true
  validates :price,presence:true
  validates :sale_price, presence:true, numericality: {less_than_or_equal_to: :price}

  before_validation :default_price

  def user_full_name
    user ? user.full_name : "Unknown User"
  end

  def default_price
    self.sale_price ||= self.price
  end

  def on_sale?
    if self.sale_price == self.price
      false
    else
      true
    end
  end

  def favourite_for(user)
    favourites.find_by_user_id user if user
  end

  # def like_for(user)
  #   likes.find_by_user_id user if user
  # end

end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
  before_action :authenticate_user!, except: [:index,:show]
  def new
    @product = Product.new
    @product.user = current_user
    # render :new
  end
  def create
    product_params = params.require(:product).permit([:title,:description,:price,:sale_price,:category_id])
    @product = Product.new(product_params)
    if @product.save
     # render :show
     # redirect_to question_path({id: @question.id})
     redirect_to product_path(@product)
   else
     # this will render `app/views/questions/new.html.erb` because the default
     # in this action is to render `app/views/questions/create.html.erb`
     render :new
   end
  end
  def show
    @product = Product.find params[:id]
    @comment = Comment.new
    respond_to do |format|
      format.html { render } # render questions/show.html.erb
      # format.json { render json: @product.to_json }
      format.xml  { render xml: @product.to_xml }
    end
    if @product.category_id
      @category = Category.find(@product.category_id).name
    else
        @category = "Not Specify"
    end
  end
  def index
    @products = Product.order("id").all
    respond_to do |format|
      format.html{render}
      format.json { render json: @products.to_json(include: :comments) }
    end
  end
  def edit
    @product = Product.find params[:id]
  end
  def update
    @product = Product.find params[:id]
    product_params = params.require(:product).permit([:title,:description,:price])
    if @product.update product_params
      @product.save
      redirect_to product_path(@product)
    else
      render :edit
    end
  end
  def destroy
    @product = Product.find params[:id]
    @product.destroy
    redirect_to products_path
  end

  # private
  #
  # def user_favourite
  #   @user_favourite ||= @product.favourite_for(current_user)
  # end
  # helper_method :user_favourite
  #
  # def user_like(c)
  # Like.where(["user_id = ? and comment_id =?", current_user.id, c])[0] if current_user
  # end
  # helper_method :user_like

end

app/helpers/products_helper.rb
module ProductsHelper
end

app/views/products/_form.html.erb
<%= form_for @product do |f|%>
<div>
  <%= f.label :title%>
  <%= f.text_field :title%>
</div>
  <div>
    <%= f.label :description%>
    <%= f.text_field :description%>
  </div>
  <div>
    <%= f.label :price%>
    <%= f.number_field :price,min:0%>
  </div>
  <div class="">
    <%= f.label :sale_price%>
    <%= f.number_field :sale_price,min:0%>
  </div>
  <div class="">
    <%= f.label :category%>
    <%= f.collection_select :category_id, Category.order(:name),:id,:name,prompt: "Select a Category" %>
  </div>
  <%= f.submit %>
<% end %>

app/views/products/create.html.erb
<h1>Thank you!</h1>

app/views/products/edit.html.erb
<h1>Edit Product Information</h1>
<%= form_for @product do |f|%>
<div>
  <%= f.label :title%>
  <%= f.text_field :title%>
</div>
  <div>
    <%= f.label :description%>
    <%= f.text_field :description%>
  </div>
  <div>
    <%= f.label :price%>
    <%= f.number_field :price,min:0%>
  </div>
  <div class="">
    <%= f.label :sale_price%>
    <%= f.number_field :sale_price,min:0%>
  </div>
  <%= f.submit %>
<% end %>

app/views/products/index.html.erb
<h1>Products List</h1>
<table style="width:100%;">
  <tbody>
    <tr>
      <td>
        Product Name:
      </td>
      <td>
        Currency:
      </td>
    </tr>
    <% @products.each do |p|%>
    <tr>
    <td style="width:30%">
      <%= link_to p.title, product_path(p) %>
    </td>
    <td>
      $ <%= p.sale_price%>
    </td>
    </div>
  </tr>
    <% end %>
  </tbody>
</table>

app/views/products/new.html.erb
<h1>Products Form</h1>

<%= render "form"%>

app/views/products/show.html.erb
<h1><%= @product.title %></h1>
<h2><%= @category%></h2>
<p>
  <%= @product.description %>
</p>
<p>
  Price: $<%= @product.sale_price %>
</p>
<p>
  Created By:<%= @product.user_full_name%>
</p>
<p>
  <%= link_to "Edit", edit_product_path(@product) %>
  <%= link_to "Delete", product_path(@product),method: :delete,data: {confirm: "Are you sure?"} %>
</p>
<hr>
<div id="product-favourite">
  <%= render "/favourites/favourite"%>
</div>

<hr>
<h2>Comments</h2>
 <div id="comment">
   <%= render "/comments/form", comment: @comment %>
 </div>
<hr>
<div id="comment-list">
<% @product.comments.each do |c|%>
    <%= render "/comments/list", c: c %>
<%end%>
</div>