config/routes.rb
Rails.application.routes.draw do

  get "/products/new" => "products#new", as: :new_product
  post "/products" => "products#create", as: :products
  get "/products/:id" => "products#show", as: :product
  get "/products" => "products#index"
  get "/products/:id/edit" => "products#edit", as: :edit_product
  patch "/products/:id" => "products#update"
  delete "/products/:id" => "products#destroy"

  resources :products do
    resources :comments, only: [:create,:destroy,:index] do
      resources :likes, only: [:create, :destroy]
    end
    resources :favourites, only: [:create,:destroy]
    end
    resources :favourites, only: :index
  resources :sessions, only: [:new,:create,:destroy]
  resources :users, only: [:new,:create, :destroy]

  root "products#index"

end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Amazon</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
  <link href="http://netdna.bootstrapcdn.com/bootstrap/3.3.6/css/bootstrap.css" rel="stylesheet">
<link href="path/to/css/star-rating.css" media="all" rel="stylesheet" type="text/css" />

<!-- optionally if you need to use a theme, then include the theme file as mentioned below -->
<link href="path/to/css/theme-krajee-svg.css" media="all" rel="stylesheet" type="text/css" />

<script src="//ajax.googleapis.com/ajax/libs/jquery/2.1.0/jquery.js"></script>
<script src="path/to/js/star-rating.js" type="text/javascript"></script>

<!-- optionally if you need translation for your language then include locale file as mentioned below -->
<script src="path/to/js/star-rating_locale_{lang}.js"></script>
</head>
<body>
<%= link_to "Home", products_path %> |
<%= link_to "New Product", new_product_path %> |
<% if user_signed?%>
 Hello, <%= current_user.full_name%> |
 <%= link_to "Your Favourite", favourites_path %> |
 <%= link_to "Sign Out", session_path(session[:user_id]), method: :delete%>
<% else %>
<%= link_to "Sign In", new_session_path%> |
<%= link_to "Sign Up", new_user_path%>
<% end %>
<div class="">
  <%= notice || alert %>
</div>
<hr>
<%= yield %>

</body>
</html>